apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: leon1223/docker-fastapi:1b9240099b8b491a5123ba82ca894e67d04b4d6c
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
