apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: leon1223/docker-fastapi:5e323836fd27c34d66db871f2449ddc4a37a0275
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
