apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: leon1223/docker-fastapi:728f608ef0cb96d56c55dcf887bf85a40532838a
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
